version: '3.7'
services:
  qdrant:
    container_name: 'qdrant-vector-db'
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
        - ./qdrant_storage:/qdrant/storage:z
